[project]
name = "social-media-docs"
description = "Social media components for Plone and Volto"
version = "1.0.0"
keywords = [
    "Social Media support for Plone",
    "documentation",
    "Plone",
    "Diátaxis",
]
readme = "README.md"
requires-python = "==3.14.*"
license = { file = "LICENSE.md" }
maintainers = [
    { name = "PloneGov-BR", email = "gov@plone.org.br" },
]
authors = [
    { name = "PloneGov-BR", email = "gov@plone.org.br" },
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "plonegovbr-socialmedia",
]

[dependency-groups]
dev = [
    "graphviz",
    "linkify-it-py",
    "myst-parser",
    "plone-sphinx-theme",
    "sphinx-autobuild",
    "sphinx-copybutton",
    "sphinx-design",
    "sphinx-examples",
    "sphinx-notfound-page",
    "sphinx-reredirects",
    "sphinx-sitemap",
    "sphinx-tippy",
    "sphinxcontrib-httpdomain",
    "sphinxcontrib-httpexample",
    "sphinxcontrib-mermaid",
    "sphinxext-opengraph",
    "vale",
]

[project.urls]
Repository = "https://github.com/plonegovbr/social-media"
Documentation = "https://plonegovbr.github.io/social-media/"

[tool.uv.sources]
plonegovbr-socialmedia = { path = "../backend/", editable = true }
