name: Social Media support for Plone CI

on:
  push:
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/backend.yml"
      - ".github/workflows/frontend.yml"
      - ".github/workflows/main.yml"
      - "devops/**"
  workflow_dispatch:

env:
  IMAGE_NAME_PREFIX: ghcr.io/plonegovbr/social-media
  NODE_VERSION: "22.x"
  PYTHON_VERSION: "3.12"

jobs:
  config:
    uses: ./.github/workflows/config.yml

  backend:
    uses: ./.github/workflows/backend.yml
    needs:
        - config
    with:
        base-tag: ${{ needs.config.outputs.base-tag }}
        image-name-prefix: ${{ needs.config.outputs.image-name-prefix }}
        image-name-suffix: backend
        python-version: ${{ needs.config.outputs.python-version }}
        plone-version: ${{ needs.config.outputs.plone-version }}
    if: ${{ needs.config.outputs.backend == 'true' }}
    permissions:
      contents: read
      packages: write

  frontend:
    uses: ./.github/workflows/frontend.yml
    needs:
        - config
    with:
        base-tag: ${{ needs.config.outputs.base-tag }}
        image-name-prefix: ${{ needs.config.outputs.image-name-prefix }}
        image-name-suffix: frontend
        node-version: ${{ needs.config.outputs.node-version }}
        volto-version: ${{ needs.config.outputs.volto-version }}
    if: ${{ needs.config.outputs.frontend == 'true' }}
    permissions:
      contents: read
      packages: write
